version: "3.8"

services:
  data_creation:
    build:
      context: ../data-creation
      dockerfile: ../docker/Dockerfile-data-creation
    container_name: data_creation_v1
    volumes:
      - ../data-creation/files:/app/files
      - ../data-creation/output:/app/output
      - ../data-creation/wind:/app/wind
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:15-alpine3.21
    container_name: postgres_db
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: race_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.56.x
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: race_data
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin123
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    restart: "no"

volumes:
  postgres_data:
